version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: milkstgo
    ports:
      - "5432:5432"

  milkstgo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: milkstgo_backend
    container_name: milkstgo_backend
    depends_on:
      - postgres-db
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/milkstgo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    deploy:
      restart_policy:
        condition: on-failure
  zap:
    image: owasp/zap2docker-weekly
    container_name: owasp_zap
    ports:
      - "8081:8080"  
    environment:
      - ZAP_PORT=8080  
    command: zap.sh -daemon -host 0.0.0.0 -port 8080  