version: "3.8"
services:
  nginx:
      image: nginx:latest
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - milkstgo

  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: milkstgo
    ports:
      - "5432:5432"

  milkstgo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: milkstgo
    container_name: milkstgo
    depends_on:
      - postgres-db
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/milkstgo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure